# 高级商务数据分析 — NumPy 专题
**授课教师：王军**  
北京外国语大学 国际商学院 管理科学与工程系


## Jupyter Notebook 常用快捷键
**命令模式（按 Esc 键）：**
1. `Enter`：转入编辑模式
2. `Shift + Enter`：运行本单元，选中下个单元
3. `Ctrl + Enter`：运行本单元
4. `Alt + Enter`：运行本单元，在其下插入新单元
5. `Y`：单元转入代码状态
6. `M`：单元转入 Markdown 状态
7. `A`：在上方插入新单元
8. `B`：在下方插入新单元
9. `D`（双击）：删除选中的单元


## NumPy 库简介
- **NumPy**（Numerical Python 的简称）是一个专门用来做科学计算的库，主要用在**多维数组（矩阵）**方面的处理。
- NumPy 是基础的科学计算库，Python 其余的科学计算扩展大部分都是以此为基础。

**特点：**
1. NumPy 内置了**并行运算**功能，当系统有多个核心，利用 NumPy 做某种计算时，NumPy 会自动做并行计算。
2. NumPy 底层使用 **C 语言**开发，效率远高于纯 Python 代码。
3. 有一个强大的 **N 维数组对象 Array**（一个类似于列表的对象）。
4. 实用的**线性代数、傅里叶变换和随机数生成函数**。

**安装：**  `pip install numpy`


## NumPy 数组与 Python 列表的性能对比
分别利用 list 和 NumPy 的数组，创建含有 100000 个元素的数组或列表：
`[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, …]`

对比二者的时间。

In [1]:
# 对多个数字求平方，时间对比
import time

In [8]:
# list 方式
t1 = time.time()
a = [x**2 for x in range(100000)]
t2 = time.time()
print('List 耗时:', t2 - t1)
print(t1, t2)

List 耗时: 0.003385782241821289
1779638243.84036 1779638243.8437457


In [4]:
# NumPy array 方式
import numpy as np
t1 = time.time()
b = np.arange(100000)**2
t2 = time.time()
print('NumPy 耗时:', t2 - t1)

NumPy 耗时: 0.00033473968505859375


In [7]:
a = np.arange(10)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 数组的创建
NumPy 中的数组使用跟 Python 中的列表非常类似。区别如下：
- 一个列表中可以存储多种数据类型（如 `a = [1, 'a']`），而**数组只能存储同种数据类型**。
- 数组特有：当多维数组中所有的数据都是数值类型时，相当于线性代数中的**矩阵**，可以进行相互间的运算。

**创建数组的方法：**
1. 使用 `np.array()`：可以传入列表、元组、range 等参数
2. 使用 `np.arange()`，类似于 Python 中的 `range`
3. 使用 `np.random` 生成随机数的数组
4. 使用函数生成特殊的数组（zeros, ones, full, eye 等）

In [9]:
# 方法1：使用 np.array
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))

# 不同类型元素会自动统一
a1 = np.array([1.0, 2, 3])
print(a1)

# 传入 range
a1 = np.array(range(100))
print(a1)

[1 2 3]
<class 'numpy.ndarray'>
[1. 2. 3.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
# 方法2：使用 arange（注意：不要将 arange 和 range 混淆）
a2 = np.arange(1, 21)        # 左闭右开
print(a2)

a2 = np.arange(1, 21, 2)     # 步长为2
print(a2)

a2 = np.arange(1, 21, -1)    # 步长为负但起始<结束 → 空数组
print(a2)

a2 = np.arange(21, 1, -1)    # 反向
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]
[]
[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [11]:
# 方法3：使用 np.random
a3 = np.random.random()       # 随机生成 0-1 之间的小数
a3

0.30896835876997364

In [12]:
# 指定行列
a3 = np.random.random((3, 4))
a3

array([[0.72194292, 0.76576142, 0.66536049, 0.93406906],
       [0.29523564, 0.19084497, 0.89583526, 0.54795356],
       [0.98749   , 0.96954186, 0.5275453 , 0.40791041]])

In [16]:
# 随机整数
a3 = np.random.randint(1, 20, size=(2, 4))
a3

array([[ 1,  5,  7,  6],
       [19, 19,  9,  5]], dtype=int32)

In [14]:
# 方法4：特殊数组
# np.zeros((2,3))   - 全0数组
# np.ones((3,2))    - 全1数组
# np.full((3,4),9)  - 指定填充值的数组
np.eye(4)            # 单位矩阵（对角线为1，其余为0）

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# 测试 full
np.full((3, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 数组中的元素类型（dtype）
因为数组中只能存储同一种数据类型，因此可以通过 `dtype` 获取数组中的元素的数据类型。
NumPy 中关于数值的类型比 Python 内置的多得多（原因是基于 C 语言实现，为了高效处理海量数据而设计）。

### NumPy 数据类型一览

| 数据类型 | 描述 | 唯一标识符 |
|---------|------|----------|
| bool | 用一个字节存储的布尔类型 | `'b'` |
| int8 | 1字节，-128 至 127 | `'i1'` |
| int16 | 2字节，-32768 ~ 32767 | `'i2'` |
| int32 | 4字节，约 ±21亿 | `'i4'` |
| int64 | 8字节 | `'i8'` |
| uint8 | 无符号整数，0 至 255 | `'u1'` |
| uint16 | 无符号整数，0 至 65535 | `'u2'` |
| float16 | 半精度浮点数 | `'f2'` |
| float64 | 双精度浮点数 | `'f8'` |
| complex64 | 复数，两个 32 位浮点 | `'c8'` |
| complex128 | 复数，两个 64 位浮点 | `'c16'` |
| object\_ | Python 对象 | `'O'` |
| string\_ | 字符串 | `'S'` |
| unicode\_ | Unicode 类型 | `'U'` |


### 为什么需要不同的整数类型？

**位（bit）与字节（byte）：** 1 byte = 8 bit

- **int8**：1 字节，8 位，范围 -128 ~ 127
- **int16**：2 字节，16 位
- **int32**：4 字节，32 位

> 例如存储数字 **77**（二进制 `1001101`）：
> - int8：`01001101`（1 字节）
> - int16：`00000000 01001101`（2 字节）
> - int32：`00000000 00000000 00000000 01001101`（4 字节）

如果存储上百亿个数字且都在 -128~127 之间，使用 int8 比 int32 可节省约 **28G** 内存！

In [ ]:
# 查看数组中元素的 dtype
a = np.array([1, 2, 3])
print(a.dtype)  # Windows 下一般默认是 int32

In [ ]:
# object 类型 —— 存储类的实例
class Person(object):
    def __init__(self, name, score):
        self.name = name
        self.score = score

p1 = Person('Mike', 60)
p2 = Person('Jordan', 100)
a_object = np.array([p1, p2])
print(a_object.dtype)

In [ ]:
# 指定 dtype
a1 = np.array([1, 2, 3], dtype=np.int8)
print(a1.dtype)

In [ ]:
# 查看元素所占内存大小（itemsize，单位：字节）
print('int32 元素:', a.itemsize, '字节')
print('int8 元素:', a1.itemsize, '字节')
print('object 元素:', a_object.itemsize, '字节')

In [ ]:
# 修改已有数组的 dtype（astype 不改变原数组）
a = np.array([1, 2, 333])
print('原始 dtype:', a.dtype)
a1 = a.astype(np.int8)
print('转换后 dtype:', a1.dtype)
print(a1)  # 注意：333 → 77（溢出！因为 int8 只能存 -128~127）

## 数组的属性
- `size`：数组中元素的**总个数**
- `ndim`：数组的**维度**（不是行数！）
- `shape`：数组的**形状**（返回元组，元素个数代表维度数）
- `itemsize`：每个元素所占的字节数

### 数组的大小（size）与形状（shape）

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('元素总数:', a.size)
print('形状:', a.shape)

In [ ]:
# 三维数组示例
a = np.array([
    [[1, 2, 3], [4, 4, 5]],
    [[3, 4, 5], [3, 3, 9]],
])
print(a)
print('形状:', a.shape)

### 数组的维数（ndim）
- 一维数组：`[1, 2, 3, 4, 5]`
- 二维数组：`[[1,2,3],[4,5,6],[7,8,9]]`
- 三维数组：`[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],...]`

In [ ]:
# 查看维度
a1 = np.arange(1, 10, 2)
a2 = np.zeros((3, 4))
print(a1, '→ ndim:', a1.ndim)
print('-' * 40)
print(a2, '→ ndim:', a2.ndim)

In [ ]:
# 三维数组
a3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
])
print(a3)
print('ndim:', a3.ndim)

### 数组的形状（shape）与 reshape

In [ ]:
# 不同维度的 shape
print('a1:', a1.shape)   # 一维
print('a2:', a2.shape)   # 二维
print('a3:', a3.shape)   # 三维

In [ ]:
# reshape：修改数组形状，不会修改原数组
a1 = np.arange(12)
print('原始:', a1)

a2 = a1.reshape((3, 4))   # 二维，3行4列
print('3×4:', a2)

a3 = a1.reshape((2, 3, 2)) # 三维，2块，每块3行2列
print('2×3×2:', a3)

a4 = a2.reshape(12)       # 变回一维
print('一维:', a4)

a5 = a1.reshape((1, 12))  # 注意：这是一个二维数组！
print('1×12 (二维):', a5)

In [ ]:
# resize：会直接在原数组上修改（与 reshape 不同）
print('原始 shape:', a.shape)
a.resize((2, 6))
print('resize 后:', a)
print('新 shape:', a.shape)

In [ ]:
# flatten 与 ravel：将多维数组转为一维
a = np.random.randint(0, 10, size=(3, 4))
print(a)

print('flatten:', a.flatten())
print('ravel:', a.ravel())

In [ ]:
# flatten vs ravel 的关键区别
# flatten 返回的是深拷贝，修改不影响原数组
a3 = a.flatten()
a3[3] = 100
print('修改 flatten 后原数组不变:')
print(a)

# ravel 返回的是视图（浅拷贝），修改会影响原数组
a3 = a.ravel()
a3[3] = 999
print('修改 ravel 后原数组也变了:')
print(a)

## 数组的拷贝
三种拷贝方式（类比内存中栈区和堆区的关系）：
- **不拷贝**（`b = a`）：两个变量指向同一对象
- **浅拷贝 / 视图 View**（`c = a.view()`）：新对象，但共享数据
- **深拷贝**（`d = a.copy()`）：完全独立的副本

In [ ]:
# 不拷贝
a = np.array([1, 2, 3])
b = a
print('a is b:', a is b)

In [ ]:
# 浅拷贝（View）
c = a.view()
print('a is c:', a is c)
a[0] = 100
print('a:', a)
print('c（跟随变化）:', c)

In [ ]:
# 深拷贝（Copy）
d = a.copy()
print('d is a:', d is a)
d[0] = 200
print('a（不变）:', a)
print('d（独立）:', d)

## 索引和切片

**最根本的规则：找最外层的逗号（即最外层中括号下的逗号），逗号前是行，后是列。如果没有最外层逗号，就只表示取行。**

- 获取**连续**的行或列 → 用切片（`:`）
- 获取**离散**的行或列 → 用中括号括起来（花式索引）

In [ ]:
# 1. 一维数组（和 list 非常相似）
a = np.arange(10)
print('a[0]:', a[0])
print('a[4:6]:', a[4:6])
print('偶数:', a[::2])

In [ ]:
# 2. 二维数组
a = np.random.randint(0, 10, size=(4, 6))
print(a)

In [ ]:
# 取一整行
print('第3行:', a[2])

In [ ]:
# 取连续多行
print('第2~3行:\n', a[1:3])

# 取不连续的行（花式索引）
print('第1行和第3行:\n', a[[0, 2]])

In [ ]:
# 行列一起查找
print('第2行第2列:', a[1, 1])

In [ ]:
# 获取数据块（连续的行和列）
print(a)
print('\n第2~3行，第5~6列:\n', a[1:3, 4:6])

In [ ]:
# 不连续的数据块说明（对比理解）
# a[[1,3]][:, [4,5]] 先取第2和第4行，再取第5和第6列 → 得到2×2
# a[[1,3], [4,5]]  取(第2行,第5列)和(第4行,第6列) → 得到1×2（逐个配对！）
print('逐个配对:', a[[1, 3], [4, 5]])
print('先取行再取列:\n', a[[1, 3]][:, [4, 5]])

In [ ]:
# 获取某一列的所有数据
print('第2~3列:\n', a[:, 1:3])
print('\n第2列和第4列（不连续）:\n', a[:, [1, 3]])

### 课堂练习
创建一个 4×5 的二维 NumPy 数组，元素为 0 到 19 的整数（按行优先填充）。使用花式索引，选取**第 0 行和第 3 行**，以及**第 1 列和第 4 列**，构成一个 2×2 的子数组。

In [ ]:
# 课堂练习
a = np.arange(20).reshape((4, 5))
print(a)

# 错误写法：a[[0,3],[1,4]]  → 这样是逐个配对，不是行列交叉
# 正确写法：先取行，再取列
result = a[[0, 3]][:, [1, 4]]
print('\n2×2 子数组:\n', result)

## 布尔索引
使用布尔值（True/False）来选择数组中符合条件的元素。

In [ ]:
# 基本用法
a = np.array([1, 2, 3])
b = np.array([True, True, False])
a[b]

In [ ]:
# 条件筛选
a = np.array([1, 2, 3, 4, 5, 6])
# 大于等于2且小于5的数据（注意：每个条件需要用括号括起来！）
a[(a >= 2) & (a < 5)]

In [ ]:
# 一维数组的布尔索引
a = np.arange(7)
print(a)
a_index = np.array([True, True, False, False, True, False, False])
print(a[a_index])

In [ ]:
# 二维数组的布尔索引（一维布尔数组 → 取行）
a = np.arange(28).reshape((7, 4))
print(a)
print('\n取第0,1,4行:\n', a[a_index])

In [ ]:
# 二维数组的布尔索引（二维布尔数组 → 取元素，展平返回）
a = np.arange(28).reshape((4, 7))
a_index = np.array([
    [False, True, False, False, True, False, False],
    [False, True, False, False, True, False, False],
    [False, True, False, False, True, False, False],
    [False, True, False, False, True, False, False]])
print(a)
print('\n按布尔矩阵取值:', a[a_index])

In [ ]:
# 更常见的用法：用条件生成布尔矩阵
print('哪些元素 < 10:\n', a < 10)
print('\n所有 < 10 的元素:', a[a < 10])

# 多个条件（与：&，或：|）
print('\n >5 且 <10 的元素:', a[(a > 5) & (a < 10)])

## 数组值的替换

In [ ]:
# 方法1：通过索引或切片
a = np.random.randint(0, 10, size=(3, 5))
print('原始:\n', a)

# 替换一整行
a[1] = 0
print('第2行全变0:\n', a)

# 替换一整行为不同值
a[1] = np.array([1, 2, 3, 4, 5])
print('第2行替换为1~5:\n', a)

# 替换某一列
a[:, 0] = 0
print('第1列全变0:\n', a)

In [ ]:
# 方法2：通过条件替换
a = np.random.randint(0, 10, size=(3, 5))
print('原始:\n', a)
a[a < 3] = -1
print('\n把 <3 的元素替换为 -1:\n', a)

In [ ]:
# 方法3：使用 where
a = np.random.randint(0, 10, size=(3, 5))
print('原始:\n', a)
# where(条件, 满足时的值, 不满足时的值)
result = np.where(a < 5, 0, 1)
print('\n<5 → 0, >=5 → 1:\n', result)

## 数组的叠加（Stacking）
- `np.vstack()`：垂直叠加（vertical stack），按行堆叠
- `np.hstack()`：水平叠加（horizontal stack），按列堆叠

In [ ]:
# 数组叠加
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('a:\n', a)
print('b:\n', b)

print('vstack（垂直叠加）:\n', np.vstack([a, b]))
print('hstack（水平叠加）:\n', np.hstack([a, b]))

## 数组的切割（Splitting）
- `np.vsplit()`：垂直切割
- `np.hsplit()`：水平切割

In [ ]:
# 数组切割
a = np.arange(16).reshape((4, 4))
print('原始:\n', a)

print('vsplit（垂直切分，分成2份）:')
for arr in np.vsplit(a, 2):
    print(arr)

print('hsplit（水平切分，分成2份）:')
for arr in np.hsplit(a, 2):
    print(arr)

## 数组的广播机制（Broadcasting）

广播机制发生在**数组与数组的计算**中。两个数组的相加、相减以及相乘都是**对应元素之间**的操作。

### 广播规则
- 如果两个数组**形状相同**，一定可以进行加减乘除运算。
- 广播主要发生在两种情况：
  1. 两个数组的**维数不相等**，但它们的**后缘维度（trailing dimension）的轴长相符**
  2. 有一方的长度为 **1**
- 如果两个数组的后缘维度（从末尾开始算起的维度）的轴长度相符，或其中一方的长度为 1，则认为是**广播兼容**的。广播会在缺失和（或）长度为 1 的维度上进行。

### 情况一：维度不同，后缘维度轴长相符

**二维 + 一维**（常见）：一维数组被广播到所有行

In [ ]:
# 二维数组与一维数组的广播
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([10, 20, 30])

print('a (3×3):\n', a)
print('b (3,):', b)
print('a + b:\n', a + b)  # b 被广播到每一行

**三维 + 二维**：二维数组被广播到所有块

In [ ]:
# 三维数组与二维数组的广播
a = np.ones((2, 3, 4))      # 形状: (2, 3, 4)
b = np.arange(12).reshape((3, 4))  # 形状: (3, 4)

print('a shape:', a.shape)
print('b shape:', b.shape)
print('a + b 结果 shape:', (a + b).shape)  # (2, 3, 4)
print(a + b)

### 情况二：维度相同，其中存在轴长为 1

轴长为 1 的维度会被**拉伸**以匹配对方。

In [ ]:
# 维度相同，轴长为1的广播
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # 形状: (3, 3)
b = np.array([[1],
              [2],
              [3]])         # 形状: (3, 1)

print('a:\n', a)
print('b:\n', b)
print('a + b:\n', a + b)  # b 的列被广播到3列

In [ ]:
# 另一个例子：列向量广播
a = np.arange(12).reshape((3, 4))
b = np.array([100, 200, 300, 400])  # 形状: (4,)
print('a:\n', a)
print('b:', b)
print('a + b:\n', a + b)  # b 被广播到所有行

## NumPy 的文件操作

三种常用方法：
1. NumPy 自带的 CSV 操作方法（`np.loadtxt` / `np.savetxt`）
2. NumPy 独有文件类型（`.npy` / `.npz`，使用 `np.save` / `np.load`）
3. 使用 Python 内置的 `csv` 模块操作 CSV 文件

> **CSV 文件**：逗号分隔值（Comma-Separated Values），有时也称为字符分隔值，因为分隔字符也可以不是逗号。以纯文本形式存储表格数据。

In [ ]:
# 保存和读取 CSV 文件
a = np.arange(12).reshape((3, 4))
print('原始数组:\n', a)

# 保存为 CSV
np.savetxt('test_data.csv', a, delimiter=',', fmt='%d')
print('已保存为 test_data.csv')

# 从 CSV 读取
b = np.loadtxt('test_data.csv', delimiter=',')
print('读取的数据:\n', b)

In [ ]:
# NumPy 独有格式（更快，保留 dtype 信息）
np.save('test_data.npy', a)
print('已保存为 test_data.npy')

b = np.load('test_data.npy')
print('读取的数据:\n', b)

In [ ]:
# 保存多个数组（npz 格式）
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6, 7])
np.savez('multi_data.npz', arr1=a1, arr2=a2)

data = np.load('multi_data.npz')
print('arr1:', data['arr1'])
print('arr2:', data['arr2'])

In [ ]:
# 清理测试文件
import os
for f in ['test_data.csv', 'test_data.npy', 'multi_data.npz']:
    if os.path.exists(f):
        os.remove(f)
print('测试文件已清理')

## 空值的处理

### 空值的种类
- **NaN**（Not a Number）：非数值，float 类型
- **INF**（Infinity）：无穷大，也是 float 类型。`np.inf` 表示正无穷大，`-np.inf` 表示负无穷大。

### NaN 的特点
1. NaN 和任何值做运算，结果都是 NaN
2. NaN 和 NaN **不相等**（`np.nan != np.nan` 这个条件是成立的！）

### 缺失值的处理方式
- 删除缺失值（删除个别值或整行）
- 用其他值进行替换（例如平均值）

In [ ]:
# NaN 的基本特性
print('np.nan + 1 =', np.nan + 1)
print('np.nan * 10 =', np.nan * 10)
print('np.nan == np.nan:', np.nan == np.nan)  # False!
print('np.nan != np.nan:', np.nan != np.nan)  # True!

In [ ]:
# 处理含 NaN 的数组
a = np.array([1, 2, np.nan, 4, np.nan, 6])
print('原始数组:', a)

# 判断哪些是 NaN
print('是否为 NaN:', np.isnan(a))

# 删除 NaN
print('删除 NaN:', a[~np.isnan(a)])

# 用平均值替换 NaN
clean_mean = np.nanmean(a)  # nanmean 会忽略 NaN
print('非 NaN 平均值:', clean_mean)
a_filled = np.where(np.isnan(a), clean_mean, a)
print('替换后:', a_filled)

In [ ]:
# INF 的处理
a = np.array([1, 2, np.inf, 4, -np.inf, 6])
print('含 INF 的数组:', a)
print('是否为 INF:', np.isinf(a))
print('有限值:', a[np.isfinite(a)])

## NumPy 中的通用函数（Universal Functions）

通用函数是对数组中每个元素进行操作的函数，效率远高于 Python 循环。

### 一元函数（Unary Functions）

| 函数 | 描述 |
|------|------|
| `np.abs` | 绝对值 |
| `np.sqrt` | 开根 |
| `np.square` | 平方 |
| `np.exp` | 计算指数 (e^x) |
| `np.log / np.log10 / np.log2` | 对数（以 e/10/2 为底） |
| `np.sign` | 符号化（>0→1, =0→0, <0→-1） |
| `np.ceil` | 向上取整 |
| `np.floor` | 向下取整 |
| `np.rint / np.round` | 四舍五入 |
| `np.modf` | 分离整数和小数部分 |
| `np.isnan` | 判断是否是 NaN |
| `np.isinf` | 判断是否是 Inf |
| `np.cos / np.sin / np.tan` | 三角函数 |


In [ ]:
# 一元函数示例
a = np.array([-4, -1, 0, 1, 4])
print('原始:', a)
print('abs:', np.abs(a))
print('sqrt:', np.sqrt(np.abs(a)))
print('square:', np.square(a))
print('sign:', np.sign(a))
print('exp:', np.exp(a[:3]))

In [ ]:
# 取整函数
a = np.array([1.2, -1.7, 3.5, -3.2, 0.0])
print('原始:', a)
print('ceil（向上取整）:', np.ceil(a))
print('floor（向下取整）:', np.floor(a))
print('rint（四舍五入）:', np.rint(a))
print('round（四舍五入）:', np.round(a))

### 二元函数（Binary Functions）

| 函数 | 描述 |
|------|------|
| `np.add` | 加法，相当于 `+` |
| `np.subtract` | 减法，相当于 `-` |
| `np.multiply` | 乘法，相当于 `*` |
| `np.divide` | 除法，相当于 `/` |
| `np.floor_divide` | 取整除法，相当于 `//` |
| `np.mod` | 取余，相当于 `%` |
| `np.greater`等 | 比较运算（>, >=, <, <=, ==, !=） |
| `np.logical_and` | 逻辑与（`&`） |
| `np.logical_or` | 逻辑或（`|`） |


In [ ]:
# 二元函数示例
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print('a:', a)
print('b:', b)
print('add:', np.add(a, b))
print('subtract:', np.subtract(a, b))
print('multiply:', np.multiply(a, b))
print('divide:', np.divide(a, b))
print('floor_divide:', np.floor_divide(b, a))
print('mod:', np.mod(b, a))
print('greater:', np.greater(a, b))

### 聚合函数（Aggregation Functions）

| 函数 | NAN 安全版本 | 描述 |
|------|-------------|------|
| `np.sum` | `np.nansum` | 求和 |
| `np.prod` | `np.nanprod` | 求积 |
| `np.mean` | `np.nanmean` | 平均值 |
| `np.std` | `np.nanstd` | 标准差 |
| `np.var` | `np.nanvar` | 方差 |
| `np.min` | `np.nanmin` | 最小值 |
| `np.max` | `np.nanmax` | 最大值 |
| `np.argmin` | `np.nanargmin` | 最小值的索引 |
| `np.argmax` | `np.nanargmax` | 最大值的索引 |
| `np.median` | `np.nanmedian` | 中位数 |


In [ ]:
# 聚合函数示例
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('a:\n', a)
print('\nsum:', np.sum(a))
print('mean:', np.mean(a))
print('std:', np.std(a))
print('min:', np.min(a), '→ 位置:', np.argmin(a))
print('max:', np.max(a), '→ 位置:', np.argmax(a))
print('median:', np.median(a))

In [ ]:
# NAN 安全版本 vs 普通版本
a = np.array([1, 2, np.nan, 4, 5])
print('含 NaN 数组:', a)
print('sum →', np.sum(a))           # → nan
print('nansum →', np.nansum(a))     # → 12（忽略 NaN）
print('mean →', np.mean(a))         # → nan
print('nanmean →', np.nanmean(a))   # → 3.0（忽略 NaN）

### 关于 axis（轴）

聚合函数和排序函数中常见的 `axis` 参数：
- **`axis=0`**：按**行**操作（沿纵向），结果的**行数**变化
- **`axis=1`**：按**列**操作（沿横向），结果的**列数**变化

> 记忆方法：axis=1 表示对每行操作，结果是列数发生变化。

In [ ]:
# axis 示例
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('a:\n', a)

print('按列求和 (axis=0, 纵向):', a.sum(axis=0))   # 每列求和 → 列数不变
print('按行求和 (axis=1, 横向):', a.sum(axis=1))   # 每行求和 → 行数不变

In [ ]:
# axis 在排序中
a = np.array([[2, 3, 1],
              [4, 3, 2],
              [3, 4, 5]])
print('原始:\n', a)
print('\n每行排序 (axis=1, 按列排):')
print(np.sort(a, axis=1))
print('\n每列排序 (axis=0, 按行排):')
print(np.sort(a, axis=0))

In [ ]:
# 布尔判断函数
a = np.array([1, 2, 3, 4, 5])
print('any(>3):', np.any(a > 3))   # 存在 >3 的元素？
print('all(>0):', np.all(a > 0))   # 全部 >0？
print('all(>3):', np.all(a > 3))   # 全部 >3？

---
## 总结

本笔记涵盖了 NumPy 的核心内容：

1. **NumPy 简介**：高性能科学计算基础库，底层用 C 实现
2. **数组创建**：`np.array`、`np.arange`、`np.random`、`np.zeros/ones/full/eye`
3. **数据类型**：dtype 系统，int8/int16/int32/int64/float 等，合理选择可节省内存
4. **数组属性**：`size`、`ndim`、`shape`、`itemsize`
5. **形状变换**：`reshape`（不改变原数组）、`resize`（改变原数组）、`flatten`/`ravel`
6. **数组拷贝**：不拷贝（`=`）、浅拷贝/View（`view()`）、深拷贝（`copy()`）
7. **索引切片**：基本索引、花式索引、布尔索引
8. **值替换**：索引替换、条件替换、`np.where`
9. **数组叠加与切割**：`vstack`/`hstack`、`vsplit`/`hsplit`
10. **广播机制**：不同形状数组间的运算规则
11. **文件操作**：CSV 读写、`.npy`/`.npz` 格式
12. **空值处理**：NaN 和 INF 的特性与处理
13. **通用函数**：一元函数、二元函数、聚合函数
14. **axis 概念**：axis=0（纵向）、axis=1（横向）
